Remove d2to1
d2to1 is deprecated (see https://github.com/embray/d2to1) and no longer
works with setuptools >= 68.0.0, so this project's wheel can no longer
be built:

  Traceback (most recent call last):
    [...]
    File "/tmp/pip-build-env-mt7emmq3/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 674, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/tmp/pip-build-env-mt7emmq3/normal/lib/python3.12/site-packages/d2to1/core.py", line 30, in d2to1
      from setuptools.dist import _get_unpatched
  ImportError: cannot import name '_get_unpatched' from 'setuptools.dist' (/tmp/pip-build-env-mt7emmq3/overlay/lib/python3.12/site-packages/setuptools/dist.py). Did you mean: 'get_unpatched'?

Port to plain modern setuptools.